### ISSUE TITLE
bug on iPhoneX

### ISSUE THREAD

**Issue by zyphs21** [zyuanming/YMPhotoBrowser#1]
Hello, When I run your project on iPhoneX. I found some UI bug. 

<img width="411" alt="2018-03-19 15 13 02" src="https://user-images.githubusercontent.com/4511324/37582859-c6400bae-2b89-11e8-8271-2e08ae34f868.png">
As you can see the picture above. The close button is invalidate.

**Comment by zyphs21** [comment]
I make a PR for this bug. Check it out #2

**Comment by zyuanming** [comment]
It's merged...
